services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mfc\Picturecredits\:
    resource: '../Classes/'
    exclude:
      - '../Classes/Domain/Model/'
      - '../Classes/Domain/Types/'
  Mfc\Picturecredits\Form\Element\TermsInputElement:
    public: true
  Mfc\Picturecredits\Form\Element\TermsRadioElement:
    public: true
